### ISSUE TITLE
评论定位的问题

### ISSUE THREAD

**Issue by hi-caicai** [unh1de/Ghost-Theme-Anatole#2]
从列表页面通过点击评论跳入到文章详情的的评论区，这个地方，估计你也用错了，如果你用的是多说的，你可以＃加多说那个div

**Comment by unh1de** [comment]
跳转了，但是由于评论框太高，跳转到顶部ID，所以下面的还是被遮住了。我放设置到最下面试试，而且还有个问题啊，Ghost 下，多说 它貌似是延时加载的，第一打开的时候，这个怎么破~ 页面内容显示完成后再加载多说的。

**Comment by hi-caicai** [comment]
@unh1de 这个我也不知道怎么破，哈哈哈，本身的逻辑就是这样的
