### ISSUE TITLE
About页面多写了字会从右向左排序

### ISSUE THREAD

**Issue by johnluo** [unh1de/Ghost-Theme-Anatole#4]
About页面多写了字会从右向左排序！或者排序交错! 

目测和Archive页的编辑形式重合了。。。 

谢谢

后台输入如图：http://v2.freep.cn/3tb_1606041938537sfd512293.jpg

前台显示如图：http://v2.freep.cn/3tb_1606041938276g5e512293.jpg

**Comment by unh1de** [comment]
不是多了的原因哦，现在修复了，你同步样式表再看看
